
-- Klassens Byggland: databasetabeller
-- 1. Opprett gratis prosjekt på supabase.com (velg gjerne EU-region)
-- 2. Åpne SQL Editor -> New query, lim inn alt dette, trykk Run
-- 3. Gå til Settings -> API og kopier Project URL + anon-nøkkelen
-- 4. Lim dem inn i index.html (SUPABASE_URL og SUPABASE_KEY)

create table if not exists public.bygg (
  id bigint generated by default as identity primary key,
  eier text not null,
  navn text not null,
  ikon text default '🏠',
  pris numeric not null,
  rente numeric not null,
  total_kostnad numeric,
  x double precision not null,
  y double precision not null,
  opprettet timestamptz default now()
);

create table if not exists public.produkter (
  id bigint generated by default as identity primary key,
  eier text not null,
  navn text not null,
  pris numeric not null,
  bilde_url text,
  opprettet timestamptz default now()
);

-- Elevene skal kunne legge inn data (ingen innlogging - de skriver bare navnet sitt)
alter table public.bygg enable row level security;
alter table public.produkter enable row level security;

drop policy if exists "alle kan lese bygg" on public.bygg;
drop policy if exists "alle kan legge inn bygg" on public.bygg;
drop policy if exists "alle kan lese produkter" on public.produkter;
drop policy if exists "alle kan legge inn produkter" on public.produkter;

create policy "alle kan lese bygg" on public.bygg for select using (true);
create policy "alle kan legge inn bygg" on public.bygg for insert with check (true);
create policy "alle kan lese produkter" on public.produkter for select using (true);
create policy "alle kan legge inn produkter" on public.produkter for insert with check (true);
